DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: 0.1

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.22
  min_vel_trans:  0.11

  max_vel_theta: 0.15
  min_vel_theta: 0.1

  acc_lim_x: 0.1
  acc_lim_y: 0.0
  acc_lim_theta: 0.1 

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.01
  latch_xy_goal_tolerance: true

# Forward Simulation Parameters
  sim_time: 2
  vx_samples: 10
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 1.0
  goal_distance_bias: 0.25
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.005

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
