stamped: true
inputs:
  linear:
    x: axis_left_y
  angular:
    # Use L2 and R2 for rotation
    # z: axis_l2 - axis_r2
    # Use right horizontal stick for rotation
    z: axis_right_x
scales:
  linear:
    x: .35
  angular:
    z: 0.35
